// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: fluentd.proto

package proto_fluentd

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FluentdRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag    string               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Time   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Record []byte               `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *FluentdRecord) Reset() {
	*x = FluentdRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fluentd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FluentdRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FluentdRecord) ProtoMessage() {}

func (x *FluentdRecord) ProtoReflect() protoreflect.Message {
	mi := &file_fluentd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FluentdRecord.ProtoReflect.Descriptor instead.
func (*FluentdRecord) Descriptor() ([]byte, []int) {
	return file_fluentd_proto_rawDescGZIP(), []int{0}
}

func (x *FluentdRecord) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *FluentdRecord) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *FluentdRecord) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_fluentd_proto protoreflect.FileDescriptor

var file_fluentd_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x69, 0x0a, 0x0d, 0x46, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6e, 0x65, 0x72, 0x65, 0x78,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x6c, 0x75, 0x65, 0x6e, 0x74, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fluentd_proto_rawDescOnce sync.Once
	file_fluentd_proto_rawDescData = file_fluentd_proto_rawDesc
)

func file_fluentd_proto_rawDescGZIP() []byte {
	file_fluentd_proto_rawDescOnce.Do(func() {
		file_fluentd_proto_rawDescData = protoimpl.X.CompressGZIP(file_fluentd_proto_rawDescData)
	})
	return file_fluentd_proto_rawDescData
}

var file_fluentd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fluentd_proto_goTypes = []interface{}{
	(*FluentdRecord)(nil),       // 0: proto.fluentd.FluentdRecord
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_fluentd_proto_depIdxs = []int32{
	1, // 0: proto.fluentd.FluentdRecord.time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fluentd_proto_init() }
func file_fluentd_proto_init() {
	if File_fluentd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fluentd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FluentdRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fluentd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fluentd_proto_goTypes,
		DependencyIndexes: file_fluentd_proto_depIdxs,
		MessageInfos:      file_fluentd_proto_msgTypes,
	}.Build()
	File_fluentd_proto = out.File
	file_fluentd_proto_rawDesc = nil
	file_fluentd_proto_goTypes = nil
	file_fluentd_proto_depIdxs = nil
}
