// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pcounter.proto

package proto_pcounter // import "github.com/synerex/proto_pcounter"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// People Counter Service message
type PCounter struct {
	DeviceId             string               `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname             string               `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Location             string               `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Timezone             string               `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Mac                  string               `protobuf:"bytes,5,opt,name=mac,proto3" json:"mac,omitempty"`
	Hardware             string               `protobuf:"bytes,6,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Protocol             string               `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Ip                   string               `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	IpVpn                string               `protobuf:"bytes,9,opt,name=ip_vpn,json=ipVpn,proto3" json:"ip_vpn,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,10,opt,name=ts,proto3" json:"ts,omitempty"`
	Data                 []*PEvent            `protobuf:"bytes,11,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PCounter) Reset()         { *m = PCounter{} }
func (m *PCounter) String() string { return proto.CompactTextString(m) }
func (*PCounter) ProtoMessage()    {}
func (*PCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_30bcd12bcca6cecf, []int{0}
}
func (m *PCounter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCounter.Unmarshal(m, b)
}
func (m *PCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCounter.Marshal(b, m, deterministic)
}
func (dst *PCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCounter.Merge(dst, src)
}
func (m *PCounter) XXX_Size() int {
	return xxx_messageInfo_PCounter.Size(m)
}
func (m *PCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_PCounter.DiscardUnknown(m)
}

var xxx_messageInfo_PCounter proto.InternalMessageInfo

func (m *PCounter) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *PCounter) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *PCounter) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *PCounter) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *PCounter) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *PCounter) GetHardware() string {
	if m != nil {
		return m.Hardware
	}
	return ""
}

func (m *PCounter) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *PCounter) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PCounter) GetIpVpn() string {
	if m != nil {
		return m.IpVpn
	}
	return ""
}

func (m *PCounter) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *PCounter) GetData() []*PEvent {
	if m != nil {
		return m.Data
	}
	return nil
}

type PEvent struct {
	Typ                  string               `protobuf:"bytes,1,opt,name=typ,proto3" json:"typ,omitempty"`
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Seq                  uint32               `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Height               uint32               `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Dir                  string               `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
	TsExit               *timestamp.Timestamp `protobuf:"bytes,7,opt,name=ts_exit,json=tsExit,proto3" json:"ts_exit,omitempty"`
	FillLevel            uint32               `protobuf:"varint,8,opt,name=fillLevel,proto3" json:"fillLevel,omitempty"`
	DwellTime            float32              `protobuf:"fixed32,9,opt,name=dwellTime,proto3" json:"dwellTime,omitempty"`
	ExpDwellTime         float32              `protobuf:"fixed32,10,opt,name=expDwellTime,proto3" json:"expDwellTime,omitempty"`
	ObjectId             uint32               `protobuf:"varint,11,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PEvent) Reset()         { *m = PEvent{} }
func (m *PEvent) String() string { return proto.CompactTextString(m) }
func (*PEvent) ProtoMessage()    {}
func (*PEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_30bcd12bcca6cecf, []int{1}
}
func (m *PEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PEvent.Unmarshal(m, b)
}
func (m *PEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PEvent.Marshal(b, m, deterministic)
}
func (dst *PEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PEvent.Merge(dst, src)
}
func (m *PEvent) XXX_Size() int {
	return xxx_messageInfo_PEvent.Size(m)
}
func (m *PEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PEvent proto.InternalMessageInfo

func (m *PEvent) GetTyp() string {
	if m != nil {
		return m.Typ
	}
	return ""
}

func (m *PEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PEvent) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PEvent) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PEvent) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *PEvent) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *PEvent) GetTsExit() *timestamp.Timestamp {
	if m != nil {
		return m.TsExit
	}
	return nil
}

func (m *PEvent) GetFillLevel() uint32 {
	if m != nil {
		return m.FillLevel
	}
	return 0
}

func (m *PEvent) GetDwellTime() float32 {
	if m != nil {
		return m.DwellTime
	}
	return 0
}

func (m *PEvent) GetExpDwellTime() float32 {
	if m != nil {
		return m.ExpDwellTime
	}
	return 0
}

func (m *PEvent) GetObjectId() uint32 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

type PCounters struct {
	Pcs                  []*PCounter `protobuf:"bytes,1,rep,name=pcs,proto3" json:"pcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PCounters) Reset()         { *m = PCounters{} }
func (m *PCounters) String() string { return proto.CompactTextString(m) }
func (*PCounters) ProtoMessage()    {}
func (*PCounters) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_30bcd12bcca6cecf, []int{2}
}
func (m *PCounters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCounters.Unmarshal(m, b)
}
func (m *PCounters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCounters.Marshal(b, m, deterministic)
}
func (dst *PCounters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCounters.Merge(dst, src)
}
func (m *PCounters) XXX_Size() int {
	return xxx_messageInfo_PCounters.Size(m)
}
func (m *PCounters) XXX_DiscardUnknown() {
	xxx_messageInfo_PCounters.DiscardUnknown(m)
}

var xxx_messageInfo_PCounters proto.InternalMessageInfo

func (m *PCounters) GetPcs() []*PCounter {
	if m != nil {
		return m.Pcs
	}
	return nil
}

// Area counter
type ACounter struct {
	Ts                   *timestamp.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	AreaName             string               `protobuf:"bytes,2,opt,name=areaName,proto3" json:"areaName,omitempty"`
	AreaId               uint32               `protobuf:"varint,3,opt,name=areaId,proto3" json:"areaId,omitempty"`
	Count                int32                `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ACounter) Reset()         { *m = ACounter{} }
func (m *ACounter) String() string { return proto.CompactTextString(m) }
func (*ACounter) ProtoMessage()    {}
func (*ACounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_30bcd12bcca6cecf, []int{3}
}
func (m *ACounter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACounter.Unmarshal(m, b)
}
func (m *ACounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACounter.Marshal(b, m, deterministic)
}
func (dst *ACounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACounter.Merge(dst, src)
}
func (m *ACounter) XXX_Size() int {
	return xxx_messageInfo_ACounter.Size(m)
}
func (m *ACounter) XXX_DiscardUnknown() {
	xxx_messageInfo_ACounter.DiscardUnknown(m)
}

var xxx_messageInfo_ACounter proto.InternalMessageInfo

func (m *ACounter) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *ACounter) GetAreaName() string {
	if m != nil {
		return m.AreaName
	}
	return ""
}

func (m *ACounter) GetAreaId() uint32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *ACounter) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ACounters struct {
	Acs                  []*ACounter `protobuf:"bytes,1,rep,name=acs,proto3" json:"acs,omitempty"`
	IntervalSec          uint32      `protobuf:"varint,2,opt,name=intervalSec,proto3" json:"intervalSec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ACounters) Reset()         { *m = ACounters{} }
func (m *ACounters) String() string { return proto.CompactTextString(m) }
func (*ACounters) ProtoMessage()    {}
func (*ACounters) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_30bcd12bcca6cecf, []int{4}
}
func (m *ACounters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACounters.Unmarshal(m, b)
}
func (m *ACounters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACounters.Marshal(b, m, deterministic)
}
func (dst *ACounters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACounters.Merge(dst, src)
}
func (m *ACounters) XXX_Size() int {
	return xxx_messageInfo_ACounters.Size(m)
}
func (m *ACounters) XXX_DiscardUnknown() {
	xxx_messageInfo_ACounters.DiscardUnknown(m)
}

var xxx_messageInfo_ACounters proto.InternalMessageInfo

func (m *ACounters) GetAcs() []*ACounter {
	if m != nil {
		return m.Acs
	}
	return nil
}

func (m *ACounters) GetIntervalSec() uint32 {
	if m != nil {
		return m.IntervalSec
	}
	return 0
}

// retrieve message
type Retrieve struct {
	From     *timestamp.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Duration *duration.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Query    string               `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// Types that are valid to be assigned to Result:
	//	*Retrieve_PcRes
	//	*Retrieve_AcRes
	Result               isRetrieve_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Retrieve) Reset()         { *m = Retrieve{} }
func (m *Retrieve) String() string { return proto.CompactTextString(m) }
func (*Retrieve) ProtoMessage()    {}
func (*Retrieve) Descriptor() ([]byte, []int) {
	return fileDescriptor_pcounter_30bcd12bcca6cecf, []int{5}
}
func (m *Retrieve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Retrieve.Unmarshal(m, b)
}
func (m *Retrieve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Retrieve.Marshal(b, m, deterministic)
}
func (dst *Retrieve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Retrieve.Merge(dst, src)
}
func (m *Retrieve) XXX_Size() int {
	return xxx_messageInfo_Retrieve.Size(m)
}
func (m *Retrieve) XXX_DiscardUnknown() {
	xxx_messageInfo_Retrieve.DiscardUnknown(m)
}

var xxx_messageInfo_Retrieve proto.InternalMessageInfo

func (m *Retrieve) GetFrom() *timestamp.Timestamp {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Retrieve) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Retrieve) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type isRetrieve_Result interface {
	isRetrieve_Result()
}

type Retrieve_PcRes struct {
	PcRes *PCounters `protobuf:"bytes,4,opt,name=pc_res,json=pcRes,proto3,oneof"`
}

type Retrieve_AcRes struct {
	AcRes *ACounters `protobuf:"bytes,5,opt,name=ac_res,json=acRes,proto3,oneof"`
}

func (*Retrieve_PcRes) isRetrieve_Result() {}

func (*Retrieve_AcRes) isRetrieve_Result() {}

func (m *Retrieve) GetResult() isRetrieve_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Retrieve) GetPcRes() *PCounters {
	if x, ok := m.GetResult().(*Retrieve_PcRes); ok {
		return x.PcRes
	}
	return nil
}

func (m *Retrieve) GetAcRes() *ACounters {
	if x, ok := m.GetResult().(*Retrieve_AcRes); ok {
		return x.AcRes
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Retrieve) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Retrieve_OneofMarshaler, _Retrieve_OneofUnmarshaler, _Retrieve_OneofSizer, []interface{}{
		(*Retrieve_PcRes)(nil),
		(*Retrieve_AcRes)(nil),
	}
}

func _Retrieve_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Retrieve)
	// result
	switch x := m.Result.(type) {
	case *Retrieve_PcRes:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PcRes); err != nil {
			return err
		}
	case *Retrieve_AcRes:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AcRes); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Retrieve.Result has unexpected type %T", x)
	}
	return nil
}

func _Retrieve_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Retrieve)
	switch tag {
	case 4: // result.pc_res
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PCounters)
		err := b.DecodeMessage(msg)
		m.Result = &Retrieve_PcRes{msg}
		return true, err
	case 5: // result.ac_res
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ACounters)
		err := b.DecodeMessage(msg)
		m.Result = &Retrieve_AcRes{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Retrieve_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Retrieve)
	// result
	switch x := m.Result.(type) {
	case *Retrieve_PcRes:
		s := proto.Size(x.PcRes)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Retrieve_AcRes:
		s := proto.Size(x.AcRes)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*PCounter)(nil), "pcounter.PCounter")
	proto.RegisterType((*PEvent)(nil), "pcounter.PEvent")
	proto.RegisterType((*PCounters)(nil), "pcounter.PCounters")
	proto.RegisterType((*ACounter)(nil), "pcounter.ACounter")
	proto.RegisterType((*ACounters)(nil), "pcounter.ACounters")
	proto.RegisterType((*Retrieve)(nil), "pcounter.Retrieve")
}

func init() { proto.RegisterFile("pcounter.proto", fileDescriptor_pcounter_30bcd12bcca6cecf) }

var fileDescriptor_pcounter_30bcd12bcca6cecf = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x3e,
	0x14, 0xff, 0x37, 0x5d, 0xb3, 0xf4, 0xe4, 0xdf, 0x69, 0x32, 0x1f, 0x0a, 0x05, 0x41, 0x09, 0x5c,
	0x4c, 0x08, 0x65, 0xa2, 0x13, 0x0f, 0xd0, 0xb1, 0x49, 0x4c, 0x42, 0x68, 0xf2, 0x10, 0x17, 0xdc,
	0x54, 0x6e, 0x72, 0xd6, 0x1a, 0xa5, 0x89, 0x67, 0xbb, 0x5d, 0xc7, 0x15, 0x4f, 0xc6, 0x15, 0xaf,
	0xc3, 0x3b, 0x20, 0xdb, 0x71, 0x57, 0x36, 0x84, 0x76, 0xe7, 0xdf, 0x87, 0xed, 0xe3, 0xdf, 0x39,
	0x09, 0xec, 0x88, 0xbc, 0x5e, 0x54, 0x1a, 0x65, 0x26, 0x64, 0xad, 0x6b, 0x12, 0x79, 0xdc, 0x7f,
	0x36, 0xad, 0xeb, 0x69, 0x89, 0xfb, 0x96, 0x9f, 0x2c, 0xce, 0xf7, 0x35, 0x9f, 0xa3, 0xd2, 0x6c,
	0x2e, 0x9c, 0xb5, 0xff, 0xf4, 0xa6, 0xa1, 0x58, 0x48, 0xa6, 0x79, 0x5d, 0x39, 0x3d, 0xfd, 0x11,
	0x40, 0x74, 0xfa, 0xce, 0x9d, 0x46, 0x1e, 0x43, 0xb7, 0xc0, 0x25, 0xcf, 0x71, 0xcc, 0x8b, 0xa4,
	0x35, 0x68, 0xed, 0x75, 0x69, 0xe4, 0x88, 0x93, 0x82, 0xf4, 0x21, 0x9a, 0xd5, 0x4a, 0x57, 0x6c,
	0x8e, 0x49, 0xe0, 0x34, 0x8f, 0x8d, 0x56, 0xd6, 0xb9, 0x3d, 0x37, 0x69, 0x3b, 0xcd, 0x63, 0xa3,
	0x99, 0xa2, 0xbe, 0xd5, 0x15, 0x26, 0x5b, 0x4e, 0xf3, 0x98, 0xec, 0x42, 0x7b, 0xce, 0xf2, 0xa4,
	0x63, 0x69, 0xb3, 0xb4, 0xb7, 0x30, 0x59, 0x5c, 0x32, 0x89, 0x49, 0xd8, 0xdc, 0xd2, 0x60, 0xa3,
	0xd9, 0xa2, 0xf3, 0xba, 0x4c, 0xb6, 0x9d, 0xe6, 0x31, 0xd9, 0x81, 0x80, 0x8b, 0x24, 0xb2, 0x6c,
	0xc0, 0x05, 0x79, 0x00, 0x21, 0x17, 0xe3, 0xa5, 0xa8, 0x92, 0xae, 0xe5, 0x3a, 0x5c, 0x7c, 0x16,
	0x15, 0x79, 0x05, 0x81, 0x56, 0x09, 0x0c, 0x5a, 0x7b, 0xf1, 0xb0, 0x9f, 0xb9, 0x6c, 0x32, 0x9f,
	0x4d, 0xf6, 0xc9, 0x87, 0x47, 0x03, 0xad, 0xc8, 0x4b, 0xd8, 0x2a, 0x98, 0x66, 0x49, 0x3c, 0x68,
	0xef, 0xc5, 0xc3, 0xdd, 0x6c, 0xdd, 0x84, 0xd3, 0xe3, 0x25, 0x56, 0x9a, 0x5a, 0x35, 0xfd, 0x19,
	0x40, 0xe8, 0x08, 0xf3, 0x1a, 0x7d, 0x25, 0x9a, 0xe0, 0xcc, 0xd2, 0x56, 0x55, 0x34, 0x69, 0x05,
	0xbc, 0x30, 0x0e, 0x85, 0x17, 0x36, 0xa2, 0x1e, 0x35, 0x4b, 0xf2, 0x10, 0xc2, 0x19, 0xf2, 0xe9,
	0x4c, 0xdb, 0x6c, 0x7a, 0xb4, 0x41, 0xc6, 0x59, 0x70, 0xe9, 0x93, 0x29, 0xb8, 0x6c, 0x4a, 0x0f,
	0xef, 0x54, 0xfa, 0x01, 0x6c, 0x6b, 0x35, 0xc6, 0x15, 0xd7, 0x36, 0xa8, 0x7f, 0x6f, 0x08, 0xb5,
	0x3a, 0x5e, 0x71, 0x4d, 0x9e, 0x40, 0xf7, 0x9c, 0x97, 0xe5, 0x07, 0x5c, 0x62, 0x69, 0x93, 0xec,
	0xd1, 0x6b, 0xc2, 0xa8, 0xc5, 0x25, 0x96, 0xa5, 0xd9, 0x67, 0x33, 0x0d, 0xe8, 0x35, 0x41, 0x52,
	0xf8, 0x1f, 0x57, 0xe2, 0x68, 0x6d, 0x00, 0x6b, 0xf8, 0x83, 0x33, 0xd3, 0x55, 0x4f, 0xbe, 0x62,
	0xae, 0xcd, 0x74, 0xc5, 0xf6, 0xfc, 0xc8, 0x11, 0x27, 0x45, 0xfa, 0x06, 0xba, 0x7e, 0x0c, 0x4d,
	0xf2, 0x6d, 0x91, 0xab, 0xa4, 0x65, 0x83, 0x27, 0x1b, 0xc1, 0x37, 0x0e, 0x6a, 0xe4, 0xf4, 0x7b,
	0x0b, 0xa2, 0x91, 0x1f, 0x5d, 0x97, 0x4e, 0xeb, 0x4e, 0xe9, 0xf4, 0x21, 0x62, 0x12, 0xd9, 0xc7,
	0x8d, 0x49, 0xf6, 0xd8, 0xf4, 0xc3, 0xac, 0x4f, 0x8a, 0xa6, 0x49, 0x0d, 0x22, 0xf7, 0xa1, 0x63,
	0xab, 0xb0, 0x6d, 0xea, 0x50, 0x07, 0xd2, 0x33, 0xe8, 0x8e, 0x36, 0xab, 0x66, 0x7f, 0xab, 0x7a,
	0xb4, 0xae, 0x9a, 0xe5, 0x8a, 0x0c, 0x20, 0xe6, 0x06, 0x2d, 0x59, 0x79, 0x86, 0xb9, 0xbd, 0xbf,
	0x47, 0x37, 0xa9, 0xf4, 0x57, 0x0b, 0x22, 0x8a, 0x5a, 0x72, 0x5c, 0x22, 0xc9, 0x60, 0xeb, 0x5c,
	0xd6, 0xf3, 0x3b, 0xbc, 0xcc, 0xfa, 0xc8, 0x5b, 0x88, 0xfc, 0x17, 0x6e, 0xcf, 0x8e, 0x87, 0x8f,
	0x6e, 0xed, 0x39, 0x6a, 0x0c, 0x74, 0x6d, 0x35, 0xcf, 0xbb, 0x58, 0xa0, 0xbc, 0x6a, 0xbe, 0x5e,
	0x07, 0xc8, 0x6b, 0x08, 0x45, 0x3e, 0x96, 0xa8, 0xec, 0xab, 0xe3, 0xe1, 0xbd, 0xdb, 0xad, 0x50,
	0xef, 0xff, 0xa3, 0x1d, 0x91, 0x53, 0x54, 0xc6, 0xcd, 0x9c, 0xbb, 0x73, 0xd3, 0x3d, 0xda, 0x74,
	0x33, 0xe3, 0x3e, 0x8c, 0x20, 0x94, 0xa8, 0x16, 0xa5, 0x3e, 0x7c, 0xf1, 0xe5, 0xf9, 0x94, 0xeb,
	0xd9, 0x62, 0x92, 0xe5, 0xf5, 0x7c, 0x5f, 0x5d, 0x55, 0x28, 0x71, 0xe5, 0x7e, 0x58, 0x63, 0x7f,
	0xc2, 0x24, 0xb4, 0xf8, 0xe0, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xce, 0xff, 0x97, 0x0b,
	0x05, 0x00, 0x00,
}
