// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ptransit.proto

package proto_ptransit // import "github.com/synerex/proto_ptransit"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PTService struct {
	OperatorId                int32                `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	LineId                    int32                `protobuf:"varint,2,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	PastStationId             int32                `protobuf:"varint,3,opt,name=past_station_id,json=pastStationId,proto3" json:"past_station_id,omitempty"`
	StationGroupId            int32                `protobuf:"varint,4,opt,name=station_group_id,json=stationGroupId,proto3" json:"station_group_id,omitempty"`
	NextStationId             int32                `protobuf:"varint,5,opt,name=next_station_id,json=nextStationId,proto3" json:"next_station_id,omitempty"`
	NextStationName           string               `protobuf:"bytes,6,opt,name=next_station_name,json=nextStationName,proto3" json:"next_station_name,omitempty"`
	VehicleId                 int32                `protobuf:"varint,7,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Angle                     float32              `protobuf:"fixed32,8,opt,name=angle,proto3" json:"angle,omitempty"`
	Speed                     int32                `protobuf:"varint,9,opt,name=speed,proto3" json:"speed,omitempty"`
	Lat                       float32              `protobuf:"fixed32,10,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                       float32              `protobuf:"fixed32,11,opt,name=lon,proto3" json:"lon,omitempty"`
	NextArraivalTimetableTime *timestamp.Timestamp `protobuf:"bytes,12,opt,name=next_arraival_timetable_time,json=nextArraivalTimetableTime,proto3" json:"next_arraival_timetable_time,omitempty"`
	PastDepartureTime         *timestamp.Timestamp `protobuf:"bytes,13,opt,name=past_departure_time,json=pastDepartureTime,proto3" json:"past_departure_time,omitempty"`
	DelayTime                 *duration.Duration   `protobuf:"bytes,14,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	VehicleType               int32                `protobuf:"varint,15,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}             `json:"-"`
	XXX_unrecognized          []byte               `json:"-"`
	XXX_sizecache             int32                `json:"-"`
}

func (m *PTService) Reset()         { *m = PTService{} }
func (m *PTService) String() string { return proto.CompactTextString(m) }
func (*PTService) ProtoMessage()    {}
func (*PTService) Descriptor() ([]byte, []int) {
	return fileDescriptor_ptransit_693b815202311645, []int{0}
}
func (m *PTService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTService.Unmarshal(m, b)
}
func (m *PTService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTService.Marshal(b, m, deterministic)
}
func (dst *PTService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTService.Merge(dst, src)
}
func (m *PTService) XXX_Size() int {
	return xxx_messageInfo_PTService.Size(m)
}
func (m *PTService) XXX_DiscardUnknown() {
	xxx_messageInfo_PTService.DiscardUnknown(m)
}

var xxx_messageInfo_PTService proto.InternalMessageInfo

func (m *PTService) GetOperatorId() int32 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *PTService) GetLineId() int32 {
	if m != nil {
		return m.LineId
	}
	return 0
}

func (m *PTService) GetPastStationId() int32 {
	if m != nil {
		return m.PastStationId
	}
	return 0
}

func (m *PTService) GetStationGroupId() int32 {
	if m != nil {
		return m.StationGroupId
	}
	return 0
}

func (m *PTService) GetNextStationId() int32 {
	if m != nil {
		return m.NextStationId
	}
	return 0
}

func (m *PTService) GetNextStationName() string {
	if m != nil {
		return m.NextStationName
	}
	return ""
}

func (m *PTService) GetVehicleId() int32 {
	if m != nil {
		return m.VehicleId
	}
	return 0
}

func (m *PTService) GetAngle() float32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func (m *PTService) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *PTService) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *PTService) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *PTService) GetNextArraivalTimetableTime() *timestamp.Timestamp {
	if m != nil {
		return m.NextArraivalTimetableTime
	}
	return nil
}

func (m *PTService) GetPastDepartureTime() *timestamp.Timestamp {
	if m != nil {
		return m.PastDepartureTime
	}
	return nil
}

func (m *PTService) GetDelayTime() *duration.Duration {
	if m != nil {
		return m.DelayTime
	}
	return nil
}

func (m *PTService) GetVehicleType() int32 {
	if m != nil {
		return m.VehicleType
	}
	return 0
}

type PTgtfs struct {
	GtfsName             string   `protobuf:"bytes,1,opt,name=gtfs_name,json=gtfsName,proto3" json:"gtfs_name,omitempty"`
	Gtfs                 []byte   `protobuf:"bytes,2,opt,name=gtfs,proto3" json:"gtfs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PTgtfs) Reset()         { *m = PTgtfs{} }
func (m *PTgtfs) String() string { return proto.CompactTextString(m) }
func (*PTgtfs) ProtoMessage()    {}
func (*PTgtfs) Descriptor() ([]byte, []int) {
	return fileDescriptor_ptransit_693b815202311645, []int{1}
}
func (m *PTgtfs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTgtfs.Unmarshal(m, b)
}
func (m *PTgtfs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTgtfs.Marshal(b, m, deterministic)
}
func (dst *PTgtfs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTgtfs.Merge(dst, src)
}
func (m *PTgtfs) XXX_Size() int {
	return xxx_messageInfo_PTgtfs.Size(m)
}
func (m *PTgtfs) XXX_DiscardUnknown() {
	xxx_messageInfo_PTgtfs.DiscardUnknown(m)
}

var xxx_messageInfo_PTgtfs proto.InternalMessageInfo

func (m *PTgtfs) GetGtfsName() string {
	if m != nil {
		return m.GtfsName
	}
	return ""
}

func (m *PTgtfs) GetGtfs() []byte {
	if m != nil {
		return m.Gtfs
	}
	return nil
}

func init() {
	proto.RegisterType((*PTService)(nil), "ptransit.PTService")
	proto.RegisterType((*PTgtfs)(nil), "ptransit.PTgtfs")
}

func init() { proto.RegisterFile("ptransit.proto", fileDescriptor_ptransit_693b815202311645) }

var fileDescriptor_ptransit_693b815202311645 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xe5, 0xb6, 0x49, 0xe3, 0x49, 0x9a, 0xb4, 0x0b, 0x12, 0x6e, 0xf8, 0xd3, 0xb4, 0x48,
	0xc8, 0xe2, 0xe0, 0x48, 0x70, 0x81, 0x23, 0xa8, 0x12, 0x0a, 0x07, 0x54, 0xb9, 0x3e, 0xc1, 0x21,
	0xda, 0xc4, 0x53, 0x77, 0x25, 0x7b, 0x77, 0xb5, 0x5e, 0x47, 0xcd, 0xb7, 0xe5, 0xa3, 0xa0, 0x9d,
	0xf5, 0x0a, 0x0a, 0x07, 0x4e, 0x9e, 0xf9, 0xed, 0x9b, 0x27, 0x7b, 0xdf, 0x18, 0xa6, 0xda, 0x1a,
	0x2e, 0x5b, 0x61, 0x33, 0x6d, 0x94, 0x55, 0x6c, 0x14, 0xfa, 0xf9, 0x45, 0xa5, 0x54, 0x55, 0xe3,
	0x92, 0xf8, 0xa6, 0xbb, 0x5b, 0x5a, 0xd1, 0x60, 0x6b, 0x79, 0xa3, 0xbd, 0x74, 0xfe, 0xea, 0x6f,
	0x41, 0xd9, 0x19, 0x6e, 0x85, 0x92, 0xfe, 0xfc, 0xea, 0xe7, 0x11, 0xc4, 0x37, 0xc5, 0x2d, 0x9a,
	0x9d, 0xd8, 0x22, 0xbb, 0x80, 0xb1, 0xd2, 0x68, 0xb8, 0x55, 0x66, 0x2d, 0xca, 0x24, 0x5a, 0x44,
	0xe9, 0x20, 0x87, 0x80, 0x56, 0x25, 0x7b, 0x06, 0xc7, 0xb5, 0x90, 0xe8, 0x0e, 0x0f, 0xe8, 0x70,
	0xe8, 0xda, 0x55, 0xc9, 0xde, 0xc0, 0x4c, 0xf3, 0xd6, 0xae, 0x5b, 0x4b, 0xee, 0x4e, 0x70, 0x48,
	0x82, 0x13, 0x87, 0x6f, 0x3d, 0x5d, 0x95, 0x2c, 0x85, 0xd3, 0x20, 0xa9, 0x8c, 0xea, 0xb4, 0x13,
	0x1e, 0x91, 0x70, 0xda, 0xf3, 0x2f, 0x0e, 0x7b, 0x47, 0x89, 0x0f, 0x8f, 0x1c, 0x07, 0xde, 0xd1,
	0xe1, 0xdf, 0x8e, 0x6f, 0xe1, 0xec, 0x91, 0x4e, 0xf2, 0x06, 0x93, 0xe1, 0x22, 0x4a, 0xe3, 0x7c,
	0xf6, 0x87, 0xf2, 0x1b, 0x6f, 0x90, 0xbd, 0x04, 0xd8, 0xe1, 0xbd, 0xd8, 0xd6, 0xf4, 0x05, 0xc7,
	0x64, 0x17, 0xf7, 0x64, 0x55, 0xb2, 0xa7, 0x30, 0xe0, 0xb2, 0xaa, 0x31, 0x19, 0x2d, 0xa2, 0xf4,
	0x20, 0xf7, 0x8d, 0xa3, 0xad, 0x46, 0x2c, 0x93, 0x98, 0xf4, 0xbe, 0x61, 0xa7, 0x70, 0x58, 0x73,
	0x9b, 0x00, 0x29, 0x5d, 0x49, 0x44, 0xc9, 0x64, 0xdc, 0x13, 0x25, 0xd9, 0x0f, 0x78, 0x41, 0xaf,
	0xc6, 0x8d, 0xe1, 0x62, 0xc7, 0xeb, 0xb5, 0x4b, 0xc7, 0xf2, 0x4d, 0x8d, 0x54, 0x25, 0x93, 0x45,
	0x94, 0x8e, 0xdf, 0xcd, 0x33, 0x9f, 0x51, 0x16, 0x32, 0xca, 0x8a, 0x10, 0x62, 0x7e, 0xee, 0xe6,
	0x3f, 0xf5, 0xe3, 0x45, 0x98, 0x76, 0x05, 0xfb, 0x0a, 0x4f, 0xe8, 0xc6, 0x4b, 0xd4, 0xdc, 0xd8,
	0xce, 0xf4, 0x9e, 0x27, 0xff, 0xf5, 0x3c, 0x73, 0x63, 0xd7, 0x61, 0x8a, 0xbc, 0x3e, 0x00, 0x94,
	0x58, 0xf3, 0xbd, 0xb7, 0x98, 0x92, 0xc5, 0xf9, 0x3f, 0x16, 0xd7, 0xfd, 0xea, 0xe4, 0x31, 0x89,
	0x69, 0xf2, 0x12, 0x26, 0xe1, 0x46, 0xed, 0x5e, 0x63, 0x32, 0xa3, 0x3b, 0x1a, 0xf7, 0xac, 0xd8,
	0x6b, 0xbc, 0xfa, 0x08, 0xc3, 0x9b, 0xa2, 0xb2, 0x77, 0x2d, 0x7b, 0x0e, 0xb1, 0x7b, 0xfa, 0x88,
	0x22, 0x8a, 0x68, 0xe4, 0x00, 0x65, 0xc3, 0xe0, 0xc8, 0xd5, 0xb4, 0x57, 0x93, 0x9c, 0xea, 0xcf,
	0xaf, 0xbf, 0x5f, 0x56, 0xc2, 0xde, 0x77, 0x9b, 0x6c, 0xab, 0x9a, 0x65, 0xbb, 0x97, 0x68, 0xf0,
	0xc1, 0xef, 0xf2, 0x3a, 0xfc, 0x03, 0x9b, 0x21, 0xf5, 0xef, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x01, 0x2c, 0x3f, 0x26, 0x03, 0x00, 0x00,
}
