// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: fleet.proto

package proto_fleet

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FleetService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Fservice:
	//	*FleetService_ShareRide
	//	*FleetService_Deliver
	Fservice isFleetService_Fservice `protobuf_oneof:"fservice"`
}

func (x *FleetService) Reset() {
	*x = FleetService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fleet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FleetService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetService) ProtoMessage() {}

func (x *FleetService) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetService.ProtoReflect.Descriptor instead.
func (*FleetService) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0}
}

func (m *FleetService) GetFservice() isFleetService_Fservice {
	if m != nil {
		return m.Fservice
	}
	return nil
}

func (x *FleetService) GetShareRide() *FleetService_ShareRideSerivce {
	if x, ok := x.GetFservice().(*FleetService_ShareRide); ok {
		return x.ShareRide
	}
	return nil
}

func (x *FleetService) GetDeliver() *FleetService_DeliverSerivce {
	if x, ok := x.GetFservice().(*FleetService_Deliver); ok {
		return x.Deliver
	}
	return nil
}

type isFleetService_Fservice interface {
	isFleetService_Fservice()
}

type FleetService_ShareRide struct {
	ShareRide *FleetService_ShareRideSerivce `protobuf:"bytes,1,opt,name=share_ride,json=shareRide,proto3,oneof"`
}

type FleetService_Deliver struct {
	Deliver *FleetService_DeliverSerivce `protobuf:"bytes,2,opt,name=deliver,proto3,oneof"`
}

func (*FleetService_ShareRide) isFleetService_Fservice() {}

func (*FleetService_Deliver) isFleetService_Fservice() {}

type Fleet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleId int32           `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Status    int32           `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Coord     *Fleet_Coord    `protobuf:"bytes,3,opt,name=coord,proto3" json:"coord,omitempty"`
	Angle     float32         `protobuf:"fixed32,4,opt,name=angle,proto3" json:"angle,omitempty"`
	Speed     int32           `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Services  []*FleetService `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	Demands   []int32         `protobuf:"varint,7,rep,packed,name=demands,proto3" json:"demands,omitempty"`
}

func (x *Fleet) Reset() {
	*x = Fleet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fleet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fleet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fleet) ProtoMessage() {}

func (x *Fleet) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fleet.ProtoReflect.Descriptor instead.
func (*Fleet) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *Fleet) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Fleet) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Fleet) GetCoord() *Fleet_Coord {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *Fleet) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *Fleet) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Fleet) GetServices() []*FleetService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Fleet) GetDemands() []int32 {
	if x != nil {
		return x.Demands
	}
	return nil
}

type FleetService_ShareRideSerivce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Capacity       int32 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	OccupiedSeats  int32 `protobuf:"varint,2,opt,name=occupied_seats,json=occupiedSeats,proto3" json:"occupied_seats,omitempty"`
	AvailableSeats int32 `protobuf:"varint,3,opt,name=available_seats,json=availableSeats,proto3" json:"available_seats,omitempty"`
	NonSmoking     bool  `protobuf:"varint,4,opt,name=non_smoking,json=nonSmoking,proto3" json:"non_smoking,omitempty"`
	PricePerKm     int32 `protobuf:"varint,5,opt,name=price_per_km,json=pricePerKm,proto3" json:"price_per_km,omitempty"`
}

func (x *FleetService_ShareRideSerivce) Reset() {
	*x = FleetService_ShareRideSerivce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fleet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FleetService_ShareRideSerivce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetService_ShareRideSerivce) ProtoMessage() {}

func (x *FleetService_ShareRideSerivce) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetService_ShareRideSerivce.ProtoReflect.Descriptor instead.
func (*FleetService_ShareRideSerivce) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FleetService_ShareRideSerivce) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *FleetService_ShareRideSerivce) GetOccupiedSeats() int32 {
	if x != nil {
		return x.OccupiedSeats
	}
	return 0
}

func (x *FleetService_ShareRideSerivce) GetAvailableSeats() int32 {
	if x != nil {
		return x.AvailableSeats
	}
	return 0
}

func (x *FleetService_ShareRideSerivce) GetNonSmoking() bool {
	if x != nil {
		return x.NonSmoking
	}
	return false
}

func (x *FleetService_ShareRideSerivce) GetPricePerKm() int32 {
	if x != nil {
		return x.PricePerKm
	}
	return 0
}

type FleetService_DeliverSerivce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item      string  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Unit      string  `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Num       int32   `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Avail     int32   `protobuf:"varint,4,opt,name=avail,proto3" json:"avail,omitempty"`
	DemandIds []int64 `protobuf:"varint,5,rep,packed,name=demand_ids,json=demandIds,proto3" json:"demand_ids,omitempty"`
}

func (x *FleetService_DeliverSerivce) Reset() {
	*x = FleetService_DeliverSerivce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fleet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FleetService_DeliverSerivce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetService_DeliverSerivce) ProtoMessage() {}

func (x *FleetService_DeliverSerivce) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetService_DeliverSerivce.ProtoReflect.Descriptor instead.
func (*FleetService_DeliverSerivce) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FleetService_DeliverSerivce) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *FleetService_DeliverSerivce) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *FleetService_DeliverSerivce) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *FleetService_DeliverSerivce) GetAvail() int32 {
	if x != nil {
		return x.Avail
	}
	return 0
}

func (x *FleetService_DeliverSerivce) GetDemandIds() []int64 {
	if x != nil {
		return x.DemandIds
	}
	return nil
}

type Fleet_Coord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon float32 `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *Fleet_Coord) Reset() {
	*x = Fleet_Coord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fleet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fleet_Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fleet_Coord) ProtoMessage() {}

func (x *Fleet_Coord) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fleet_Coord.ProtoReflect.Descriptor instead.
func (*Fleet_Coord) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Fleet_Coord) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Fleet_Coord) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

var File_fleet_proto protoreflect.FileDescriptor

var file_fleet_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x22, 0xf2, 0x03, 0x0a, 0x0c, 0x46,
	0x6c, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x5f, 0x72, 0x69, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x46, 0x6c,
	0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x52, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x69, 0x76, 0x63, 0x65, 0x48, 0x00, 0x52, 0x09, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x52, 0x69, 0x64, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72, 0x69,
	0x76, 0x63, 0x65, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x1a, 0xc1,
	0x01, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72, 0x65, 0x52, 0x69, 0x64, 0x65, 0x53, 0x65, 0x72, 0x69,
	0x76, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12,
	0x25, 0x0a, 0x0e, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x61, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65,
	0x64, 0x53, 0x65, 0x61, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x61, 0x74, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6e, 0x5f, 0x73, 0x6d, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6e, 0x6f, 0x6e, 0x53, 0x6d, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x12, 0x20, 0x0a, 0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x6b, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x50, 0x65, 0x72,
	0x4b, 0x6d, 0x1a, 0x7f, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x69, 0x76, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69,
	0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64,
	0x49, 0x64, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x66, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x98, 0x02, 0x0a, 0x05, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2e, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x46, 0x6c,
	0x65, 0x65, 0x74, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x46, 0x6c, 0x65,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x64, 0x65, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x1a, 0x2b, 0x0a,
	0x05, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6e, 0x65, 0x72, 0x65, 0x78,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fleet_proto_rawDescOnce sync.Once
	file_fleet_proto_rawDescData = file_fleet_proto_rawDesc
)

func file_fleet_proto_rawDescGZIP() []byte {
	file_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(file_fleet_proto_rawDescData)
	})
	return file_fleet_proto_rawDescData
}

var file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fleet_proto_goTypes = []interface{}{
	(*FleetService)(nil),                  // 0: proto.fleet.FleetService
	(*Fleet)(nil),                         // 1: proto.fleet.Fleet
	(*FleetService_ShareRideSerivce)(nil), // 2: proto.fleet.FleetService.ShareRideSerivce
	(*FleetService_DeliverSerivce)(nil),   // 3: proto.fleet.FleetService.DeliverSerivce
	(*Fleet_Coord)(nil),                   // 4: proto.fleet.Fleet.Coord
}
var file_fleet_proto_depIdxs = []int32{
	2, // 0: proto.fleet.FleetService.share_ride:type_name -> proto.fleet.FleetService.ShareRideSerivce
	3, // 1: proto.fleet.FleetService.deliver:type_name -> proto.fleet.FleetService.DeliverSerivce
	4, // 2: proto.fleet.Fleet.coord:type_name -> proto.fleet.Fleet.Coord
	0, // 3: proto.fleet.Fleet.services:type_name -> proto.fleet.FleetService
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_fleet_proto_init() }
func file_fleet_proto_init() {
	if File_fleet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fleet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FleetService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fleet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fleet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fleet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FleetService_ShareRideSerivce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fleet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FleetService_DeliverSerivce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fleet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fleet_Coord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_fleet_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*FleetService_ShareRide)(nil),
		(*FleetService_Deliver)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fleet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_proto_depIdxs,
		MessageInfos:      file_fleet_proto_msgTypes,
	}.Build()
	File_fleet_proto = out.File
	file_fleet_proto_rawDesc = nil
	file_fleet_proto_goTypes = nil
	file_fleet_proto_depIdxs = nil
}
